In [40]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient('mongodb://localhost:27017/')
db = client.companies

In [41]:
with_office = db.companies.find({
    "offices":{
        "$not":{
            "$size":0
        }
    }
},{"name":1, "offices":1, "category_code":1, "founded_year":1, "number_of_employees":1})

In [42]:
df = pd.DataFrame(with_office)
df.head()

,_id,category_code,founded_year,name,number_of_employees,offices
0,52cdef7c4bab8bd675297d8b,enterprise,1996.0,AdventNet,600.0,"[{'description': 'Headquarters', 'address1': '..."
1,52cdef7c4bab8bd675297d8a,web,2005.0,Wetpaint,47.0,"[{'description': '', 'address1': '710 - 2nd Av..."
2,52cdef7c4bab8bd675297d8c,software,2005.0,Zoho,1600.0,"[{'description': 'Headquarters', 'address1': '..."
3,52cdef7c4bab8bd675297d8f,network_hosting,2005.0,Omnidrive,NaN,"[{'description': '', 'address1': 'Suite 200', ..."
4,52cdef7c4bab8bd675297d8d,news,2004.0,Digg,60.0,"[{'description': None, 'address1': '135 Missis..."

In [26]:
#print(df.columns)
#df1=df[['_id','name','category_code','founded_year','number_of_employees','offices']]
#df1.head()

In [45]:
def getFirst(data):
    data = data['offices']
#    return (len(data),data[0]['latitude'],data[0]['longitude'])

    # Only create the geoJSON object if all geodata is available
    principal = None
    if data[0]['latitude'] and data[0]['longitude']:
        principal = {
            "type":"Point",
            "coordinates":[data[0]['longitude'], data[0]['latitude']]
        }

    return {
        "totalOffices": len(data),
        "lat": data[0]['latitude'],
        "lng": data[0]['longitude'],
        "headquarters": principal
    }


main_office = df[["offices"]].apply(getFirst, result_type="expand", axis=1)

In [46]:

df_geo = pd.concat([df,main_office], axis=1)[["name","lat","lng", "headquarters","number_of_employees", "totalOffices", "category_code","founded_year"]]
df_geo

,name,lat,lng,headquarters,number_of_employees,totalOffices,category_code,founded_year
0,AdventNet,37.692934,-121.904945,"{'type': 'Point', 'coordinates': [-121.904945,...",600.0,1.0,enterprise,1996.0
1,Wetpaint,47.603122,-122.333253,"{'type': 'Point', 'coordinates': [-122.333253,...",47.0,2.0,web,2005.0
2,Zoho,37.692934,-121.904945,"{'type': 'Point', 'coordinates': [-121.904945,...",1600.0,1.0,software,2005.0
3,Omnidrive,NaN,NaN,NaN,NaN,1.0,network_hosting,2005.0
4,Digg,37.764726,-122.394523,"{'type': 'Point', 'coordinates': [-122.394523,...",60.0,1.0,news,2004.0
5,Flektor,34.025958,-118.379768,"{'type': 'Point', 'coordinates': [-118.379768,...",NaN,1.0,games_video,NaN
6,Postini,37.506885,-122.247573,"{'type': 'Point', 'coordinates': [-122.247573,...",NaN,1.0,web,1999.0
7,Geni,34.090368,-118.393064,"{'type': 'Point', 'coordinates': [-118.393064,...",18.0,1.0,web,2006.0
8,Fox Interactive Media,34.076179,-118.394170,"{'type': 'Point', 'coordinates': [-118.39417, ...",0.0,1.0,web,1979.0
9,Gizmoz,37.484130,-122.169472,"{'type': 'Point', 'coordinates': [-122.169472,...",NaN,1.0,web,2003.0
10,Lala,37.451151,-122.154369,"{'type': 'Point', 'coordinates': [-122.154369,...",NaN,1.0,games_video,NaN
11,Slacker,33.022176,-117.081406,"{'type': 'Point', 'coordinates': [-117.081406,...",NaN,1.0,music,2006.0
12,Scribd,37.789634,-122.404052,"{'type': 'Point', 'coordinates': [-122.404052,...",50.0,1.0,news,2007.0
13,StumbleUpon,37.775196,-122.419204,"{'type': 'Point', 'coordinates': [-122.419204,...",NaN,2.0,web,2002.0
14,Helio,34.057498,-118.446596,"{'type': 'Point', 'coordinates': [-118.446596,...",NaN,1.0,mobile,2005.0
15,MeetMoi,40.757929,-73.985506,"{'type': 'Point', 'coordinates': [-73.985506, ...",15.0,1.0,social,2007.0
16,Babelgum,53.344104,-6.267494,"{'type': 'Point', 'coordinates': [-6.267494, 5...",NaN,1.0,games_video,2007.0
17,Joost,40.746497,-74.009447,"{'type': 'Point', 'coordinates': [-74.0094471,...",0.0,1.0,games_video,2006.0
18,Viacom,40.757725,-73.986011,"{'type': 'Point', 'coordinates': [-73.986011, ...",NaN,1.0,web,1971.0
19,CBS,37.269175,-119.306607,"{'type': 'Point', 'coordinates': [-119.306607,...",NaN,1.0,news,1986.0
20,Twitter,37.776805,-122.416924,"{'type': 'Point', 'coordinates': [-122.4169244...",1300.0,1.0,social,2006.0
21,Plaxo,37.387845,-122.055197,"{'type': 'Point', 'coordinates': [-122.055197,...",50.0,1.0,web,2002.0
22,Facebook,37.416050,-122.151801,"{'type': 'Point', 'coordinates': [-122.151801,...",5299.0,3.0,social,2004.0
23,eBay,37.295005,-121.930035,"{'type': 'Point', 'coordinates': [-121.930035,...",15000.0,1.0,web,1995.0
24,Powerset,37.778613,-122.395289,"{'type': 'Point', 'coordinates': [-122.395289,...",60.0,1.0,search,2006.0
25,Technorati,37.779558,-122.393041,"{'type': 'Point', 'coordinates': [-122.393041,...",35.0,1.0,advertising,2002.0
26,Sparter,37.090240,-95.712891,"{'type': 'Point', 'coordinates': [-95.712891, ...",NaN,1.0,games_video,2007.0
27,Mahalo,34.017606,-118.487267,"{'type': 'Point', 'coordinates': [-118.487267,...",40.0,1.0,web,2007.0
28,Kyte,37.788482,-122.409173,"{'type': 'Point', 'coordinates': [-122.409173,...",40.0,1.0,games_video,2006.0
29,AddThis,38.926172,-77.245195,"{'type': 'Point', 'coordinates': [-77.245195, ...",120.0,6.0,advertising,2004.0
...,...,...,...,...,...,...,...,...
13714,InstantQ,37.369195,-122.036849,"{'type': 'Point', 'coordinates': [-122.036849,...",3.0,1.0,advertising,2009.0
13715,SEO Sumo,25.723408,-80.306331,"{'type': 'Point', 'coordinates': [-80.306331, ...",5.0,1.0,public_relations,2009.0
13716,NextLabs,37.553121,-122.301534,"{'type': 'Point', 'coordinates': [-122.301534,...",100.0,1.0,enterprise,2004.0
13717,Xray Imatek,NaN,NaN,NaN,NaN,1.0,biotech,NaN
13718,iGuiders,NaN,NaN,NaN,5.0,1.0,web,2008.0
13719,Optemo,NaN,NaN,NaN,NaN,1.0,web,NaN
13720,Treehouse,NaN,NaN,NaN,55.0,2.0,education,2011.0
13721,Cantimer,37.484616,-122.181753,"{'type': 'Point', 'coordinates': [-122.181753,...",NaN,1.0,None,2006.0
13722,acrossair,51.517742,-0.116537,"{'type': 'Point', 'coordinates': [-0.1165365, ...",6.0,1.0,mobile,2009.0
13723,SolarPower Israel,NaN,NaN,NaN,NaN,1.0,cleantech,NaN
13724,Cameron Health,33.448010,-117.607717,"{'type': 'Point', 'coordinates': [-117.607717,...",NaN,1.0,medical,2001.0
13725,Celestial Semiconductor,37.386417,-121.929170,"{'type': 'Point', 'coordinates': [-121.92917, ...",NaN,1.0,semiconductor,2004.0
13726,MyChances,39.394564,-119.812079,"{'type': 'Point', 'coordinates': [-119.8120795...",2.0,2.0,consulting,2009.0
13727,InSound Medical,37.512038,-121.998513,"{'type': 'Point', 'coordinates': [-121.998513,...",NaN,1.0,biotech,NaN
13728,Purfresh,37.477008,-122.151599,"{'type': 'Point', 'coordinates': [-122.151599,...",NaN,1.0,cleantech,1996.0
13729,Getyoo,50.839970,4.346472,"{'type': 'Point', 'coordinates': [4.3464721, 5...",10.0,1.0,mobile,2009.0
13730,Eazeeloans,NaN,NaN,NaN,25.0,1.0,web,2006.0
13731,DocASAP,NaN,NaN,NaN,7.0,1.0,web,2012.0
13732,EnterSys Group,29.848779,-95.504545,"{'type': 'Point', 'coordinates': [-95.5045451,...",NaN,1.0,software,2000.0
13733,Axon Solutions,40.715887,-74.033251,"{'type': 'Point', 'coordinates': [-74.033251, ...",NaN,1.0,software,2004.0
13734,Intergy,37.701940,-121.936698,"{'type': 'Point', 'coordinates': [-121.9366984...",NaN,1.0,software,2003.0
13735,Willdan Group,33.806525,-117.882314,"{'type': 'Point', 'coordinates': [-117.882314,...",385.0,1.0,other,NaN
13736,OfficialVirtualDJ,NaN,NaN,NaN,102.0,1.0,music,2009.0
13737,Contemporary Computer Services,40.775055,-73.088140,"{'type': 'Point', 'coordinates': [-73.08814, 4...",NaN,1.0,software,1974.0
13738,QSGI,26.705331,-80.041395,"{'type': 'Point', 'coordinates': [-80.041395, ...",164.0,1.0,software,1967.0
13739,Oriact,47.088219,8.437163,"{'type': 'Point', 'coordinates': [8.4371634, 4...",NaN,1.0,software,2009.0
13740,Adhunk,NaN,NaN,NaN,3.0,1.0,advertising,2009.0
13741,EnteGreat Solutions,33.518885,-86.816068,"{'type': 'Point', 'coordinates': [-86.816068, ...",NaN,1.0,software,NaN
13742,AfterLogic,40.793024,-74.323554,"{'type': 'Point', 'coordinates': [-74.3235539,...",NaN,1.0,software,2002.0
13743,EnteGreat,33.407786,-86.761302,"{'type': 'Point', 'coordinates': [-86.7613019,...",NaN,1.0,enterprise,2000.0